Added uninstallation code, updated installation, and updated solver-scheduler sample config.

diff --git a/installation/uninstall b/installation/uninstall
--- a/installation/uninstall
+++ b/installation/uninstall
@@ -50,54 +50,61 @@ if [ ! -f "${_NOVA_CONF_DIR}/${_NOVA_CONF_FILE}" ] ; then
     exit 1
 fi
 
-echo "checking previous installation..."
-if [ -d "${_BACKUP_DIR}/nova" ] ; then
-    echo "It seems nova-solver-scheduler has already been installed!"
-    echo "Please check README for solution if this is not true."
+echo "checking backup..."
+if [ ! -d "${_BACKUP_DIR}/nova" ] ; then
+    echo "Could not find backup files. It is possible that the solver-scheduler has been uninstalled."
+    echo "If this is not the case, then please uninstall manually."
     exit 1
 fi
 
 echo "backing up current files that might be overwritten..."
-mkdir -p "${_BACKUP_DIR}/nova"
-mkdir -p "${_BACKUP_DIR}/etc/nova"
-cp -r "${_NOVA_DIR}/scheduler" "${_BACKUP_DIR}/nova/" && cp -r "${_NOVA_DIR}/volume" "${_BACKUP_DIR}/nova/"
+if [ -d "${_BACKUP_DIR}/uninstall" ] ; then
+    rm -r "${_BACKUP_DIR}/uninstall"
+fi
+mkdir -p "${_BACKUP_DIR}/uninstall/nova"
+mkdir -p "${_BACKUP_DIR}/uninstall/etc/nova"
+cp -r "${_NOVA_DIR}/scheduler" "${_BACKUP_DIR}/uninstall/nova/" && cp -r "${_NOVA_DIR}/volume" "${_BACKUP_DIR}/uninstall/nova/"
 if [ $? -ne 0 ] ; then
-    rm -r "${_BACKUP_DIR}/nova"
+    rm -r "${_BACKUP_DIR}/uninstall/nova"
     echo "Error in code backup, aborted."
     exit 1
 fi
-cp "${_NOVA_CONF_DIR}/${_NOVA_CONF_FILE}" "${_BACKUP_DIR}/etc/nova/"
+cp "${_NOVA_CONF_DIR}/${_NOVA_CONF_FILE}" "${_BACKUP_DIR}/uninstall/etc/nova/"
 if [ $? -ne 0 ] ; then
-    rm -r "${_BACKUP_DIR}/nova"
-    rm -r "${_BACKUP_DIR}/etc"
+    rm -r "${_BACKUP_DIR}/uninstall/nova"
+    rm -r "${_BACKUP_DIR}/uninstall/etc"
     echo "Error in config backup, aborted."
     exit 1
 fi
 
-echo "copying in new files..."
-cp -r "${_CODE_DIR}" `dirname ${_NOVA_DIR}`
+echo "restoring code to the status before installing solver-scheduler..."
+cp -r "${_BACKUP_DIR}/nova" `dirname ${_NOVA_DIR}`
 if [ $? -ne 0 ] ; then
     echo "Error in copying, aborted."
-    echo "Recovering original files..."
-    cp -r "${_BACKUP_DIR}/nova" `dirname ${_NOVA_DIR}` && rm -r "${_BACKUP_DIR}/nova"
+    echo "Recovering current files..."
+    cp -r "${_BACKUP_DIR}/uninstall/nova" `dirname ${_NOVA_DIR}`
     if [ $? -ne 0 ] ; then
-        echo "Recovering failed! Please install manually."
+        echo "Recovering failed! Please uninstall manually."
     fi
     exit 1
 fi
 
 echo "updating config file..."
-sed -i .backup -e "/scheduler_driver *=/d" "${_NOVA_CONF_DIR}/${_NOVA_CONF_FILE}"
-sed -i .backup -e "/\[DEFAULT\]/a \\
-scheduler_driver=nova.scheduler.solver_scheduler.ConstraintSolverScheduler" "${_NOVA_CONF_DIR}/${_NOVA_CONF_FILE}"
+sed -i .uninstall.backup -e "/scheduler_driver *=/d" "${_NOVA_CONF_DIR}/${_NOVA_CONF_FILE}"
 if [ $? -ne 0 ] ; then
     echo "Error in updating, aborted."
-    echo "Recovering original files..."
-    cp "${_BACKUP_DIR}/etc/nova/${_NOVA_CONF_FILE}" "${_NOVA_CONF_DIR}" && rm -r "${_BACKUP_DIR}/etc"
+    echo "Recovering current files..."
+    cp "${_BACKUP_DIR}/uninstall/etc/nova/${_NOVA_CONF_FILE}" "${_NOVA_CONF_DIR}"
     if [ $? -ne 0 ] ; then
-        echo "Recovering failed! Please install manually."
+        echo "Recovering failed! Please uninstall manually."
     fi
     exit 1
+fi
+
+echo "cleaning up backup files..."
+rm -r "${_BACKUP_DIR}/nova" && rm -r "${_BACKUP_DIR}/etc"
+if [ $? -ne 0 ] ; then
+    echo "There was an error when cleaning up the backup files."
 fi
 
 echo "restarting nova scheduler..."
@@ -108,6 +115,5 @@ if [ $? -ne 0 ] ; then
 fi
 
 echo "Completed."
-echo "See README to get started."
 
 exit 0
